
#server configuration
server:
  port: 1086
  address: localhost

datasource:
  url: jdbc:mysql://localhost:3300/test_quartz?characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
  username: username
  password: password
  driverClassName: com.mysql.jdbc.Driver




